// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Context;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20241002052607_Correcciones2")]
    partial class Correcciones2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WebApi.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("WebApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WebApi.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_GameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_GameId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("WebApi.Models.RoundsGames", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_OptionsId")
                        .HasColumnType("int");

                    b.Property<int>("Id_PlayersId")
                        .HasColumnType("int");

                    b.Property<int>("Id_RoundsId")
                        .HasColumnType("int");

                    b.Property<bool>("Victory")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Id_OptionsId");

                    b.HasIndex("Id_PlayersId");

                    b.HasIndex("Id_RoundsId");

                    b.ToTable("RoundsGames");
                });

            modelBuilder.Entity("WebApi.Models.Round", b =>
                {
                    b.HasOne("WebApi.Models.Game", "Id_Game")
                        .WithMany()
                        .HasForeignKey("Id_GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Id_Game");
                });

            modelBuilder.Entity("WebApi.Models.RoundsGames", b =>
                {
                    b.HasOne("WebApi.Models.Option", "Id_Options")
                        .WithMany()
                        .HasForeignKey("Id_OptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Player", "Id_Players")
                        .WithMany()
                        .HasForeignKey("Id_PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Round", "Id_Rounds")
                        .WithMany()
                        .HasForeignKey("Id_RoundsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Id_Options");

                    b.Navigation("Id_Players");

                    b.Navigation("Id_Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
