// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Context;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WebApi.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("WebApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WebApi.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Game")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Game");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("WebApi.Models.RoundsGames", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Options")
                        .HasColumnType("int");

                    b.Property<int>("Id_Players")
                        .HasColumnType("int");

                    b.Property<int>("Id_Rounds")
                        .HasColumnType("int");

                    b.Property<bool>("Victory")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Id_Options");

                    b.HasIndex("Id_Players");

                    b.HasIndex("Id_Rounds");

                    b.ToTable("RoundsGames");
                });

            modelBuilder.Entity("WebApi.Models.Round", b =>
                {
                    b.HasOne("WebApi.Models.Game", "Game")
                        .WithMany("Rounds")
                        .HasForeignKey("Id_Game")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("WebApi.Models.RoundsGames", b =>
                {
                    b.HasOne("WebApi.Models.Option", "Option")
                        .WithMany("RoundsGames")
                        .HasForeignKey("Id_Options")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Player", "Player")
                        .WithMany("RoundsGames")
                        .HasForeignKey("Id_Players")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Round", "Round")
                        .WithMany("RoundsGames")
                        .HasForeignKey("Id_Rounds")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("WebApi.Models.Game", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("WebApi.Models.Option", b =>
                {
                    b.Navigation("RoundsGames");
                });

            modelBuilder.Entity("WebApi.Models.Player", b =>
                {
                    b.Navigation("RoundsGames");
                });

            modelBuilder.Entity("WebApi.Models.Round", b =>
                {
                    b.Navigation("RoundsGames");
                });
#pragma warning restore 612, 618
        }
    }
}
